#!/usr/bin/env ruby
require './lib/dirsplit'
require './lib/dirsplit/optparse'

splitter = Dirsplit.new
splitter.parse_options(ARGV)
splitter.preflight

if splitter.errors.count > 0
  splitter.errors.each do |error|
    puts "Error: #{error}"
  end
  exit 1
else
  splitter.gather_files
  splitter.copy_files
end
