#!/usr/bin/env ruby
require './lib/dirsplit'
require './lib/dirsplit/optparse'

splitter = Dirsplit.new
splitter.parse_options

if splitter.errors
  splitter.errors.each do |error|
    puts "Error: #{error}"
  end
  exit 1
end
